Revert "Install binary package of cryptography"
This reverts commit 63c526bd3180227143a8134343963b26d1b1007e.

On Alpine, we get the following error message:

  Collecting cryptography>=2.3 (from pyopenssl>=16.0.0->twisted[tls])
    ERROR: Could not find a version that satisfies the requirement cryptography>=2.3 (from pyopenssl>=16.0.0->twisted[tls]) (from versions: none)
  ERROR: No matching distribution found for cryptography>=2.3 (from pyopenssl>=16.0.0->twisted[tls])
  make[1]: Leaving directory
    `/home/travis/build/cjolowicz/docker-buildbot-worker/alpine/3.9/x86_64'