Install Python and OpenSSL from source on Debian 8
Twisted dropped Python 3.4 support.

  ERROR: Command errored out with exit status 1:
    command: /usr/bin/python3 -c 'import sys, setuptools, tokenize;
               sys.argv[0] =
               '"'"'/tmp/pip-install-wme7cdbo/twisted/setup.py'"'"';
               __file__='"'"'/tmp/pip-install-wme7cdbo/twisted/setup.py'"'"';f=getattr(tokenize,
               '"'"'open'"'"',
               open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
               '"'"'\n'"'"');f.close();exec(compile(code, __file__,
               '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
        cwd: /tmp/pip-install-wme7cdbo/twisted/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wme7cdbo/twisted/setup.py", line 20, in <module>
        setuptools.setup(**_setup["getSetupArgs"]())
      File "<string>", line 257, in getSetupArgs
      File "<string>", line 208, in _checkPythonVersion
    ImportError: Twisted on Python 3 requires Python 3.5 or later.

Python 3.6.8 does not build against the OpenSSL shipped with Debian 8.

  #7 81.14 gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv
             -O3 -Wall    -std=c99 -Wextra -Wno-unused-result
             -Wno-unused-parameter -Wno-missing-field-initializers
             -I. -I./Include -Wl,-R/lib  -fPIC -DPy_BUILD_CORE  -c
             ./Modules/xxsubtype.c -o Modules/xxsubtype.o
  #7 81.20 ./Modules/_ssl.c:72:25: fatal error: openssl/rsa.h: No such file or
             directory
  #7 81.20  #include "openssl/rsa.h"
  #7 81.20                          ^
  #7 81.20 compilation terminated.
  #7 81.27 gcc -pthread -c -Wno-unused-result -Wsign-compare -DNDEBUG -g
             -fwrapv -O3 -Wall    -std=c99 -Wextra -Wno-unused-result
             -Wno-unused-parameter -Wno-missing-field-initializers   -I.
             -I./Include -Wl,-R/lib  -fPIC -DPy_BUILD_CORE -o Python/frozen.o
             Python/frozen.c
  #7 81.39 Makefile:1808: recipe for target 'Modules/_ssl.o' failed
  #7 81.39 make: *** [Modules/_ssl.o] Error 1
  #7 81.39 make: *** Waiting for unfinished jobs....
  ------
  failed to solve with frontend dockerfile.v0: failed to build LLB: executor
    failed running [/bin/sh -c set -ex;     cd /usr/local/src;
    curl
    https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz
    -LO;     tar -xf Python-$PYTHON_VERSION.tgz;
    rm -f Python-$PYTHON_VERSION.tgz;     cd Python-$PYTHON_VERSION;
    patch -p1 < ../python-use-local-openssl.patch;     ./configure
    --enable-loadable-sqlite-extensions         --enable-shared
    --with-system-expat         --with-system-ffi         --without-ensurepip
    CPPFLAGS="$(pkg-config --cflags openssl) -Wl,-R$OPENSSL_DIR/lib"
    LDFLAGS="$(pkg-config --libs openssl) -Wl,-R$OPENSSL_DIR/lib"     ;
    make -j "$(nproc)";     make install;     ldconfig;
    find /usr/local -depth         \(             \( -type d -a \( -name test
    -o -name tests \) \)             -o             \( -type f -a \( -name
    '*.pyc' -o -name '*.pyo' \) \)         \) -exec rm -rf '{}' +     ;
    cd ..;     rm -rf Python-$PYTHON_VERSION;     python3 --version]:
    exit code: 2